/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppMetrics
 */
public class AppMetricsTest {
    private final AppMetrics model = new AppMetrics();

    /**
     * Model tests for AppMetrics
     */
    @Test
    public void testAppMetrics() {
        // TODO: test AppMetrics
    }

    /**
     * Test the property 'walletBalance'
     */
    @Test
    public void walletBalanceTest() {
        // TODO: test walletBalance
    }

    /**
     * Test the property 'moneyOut'
     */
    @Test
    public void moneyOutTest() {
        // TODO: test moneyOut
    }

    /**
     * Test the property 'connectedUsers'
     */
    @Test
    public void connectedUsersTest() {
        // TODO: test connectedUsers
    }

}
