/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckoutSessionLineItemsInner
 */
public class CheckoutSessionLineItemsInnerTest {
    private final CheckoutSessionLineItemsInner model = new CheckoutSessionLineItemsInner();

    /**
     * Model tests for CheckoutSessionLineItemsInner
     */
    @Test
    public void testCheckoutSessionLineItemsInner() {
        // TODO: test CheckoutSessionLineItemsInner
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'priceId'
     */
    @Test
    public void priceIdTest() {
        // TODO: test priceId
    }

}
