/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CheckoutSession;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckoutsessionsListAllResponse
 */
public class CheckoutsessionsListAllResponseTest {
    private final CheckoutsessionsListAllResponse model = new CheckoutsessionsListAllResponse();

    /**
     * Model tests for CheckoutsessionsListAllResponse
     */
    @Test
    public void testCheckoutsessionsListAllResponse() {
        // TODO: test CheckoutsessionsListAllResponse
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    public void hasMoreTest() {
        // TODO: test hasMore
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
