/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PayoutsSendPayoutRequestDelivery;
import com.konfigthis.client.model.PayoutsSendPayoutRequestPayee;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayoutsSendPayoutRequest
 */
public class PayoutsSendPayoutRequestTest {
    private final PayoutsSendPayoutRequest model = new PayoutsSendPayoutRequest();

    /**
     * Model tests for PayoutsSendPayoutRequest
     */
    @Test
    public void testPayoutsSendPayoutRequest() {
        // TODO: test PayoutsSendPayoutRequest
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'payee'
     */
    @Test
    public void payeeTest() {
        // TODO: test payee
    }

    /**
     * Test the property 'delivery'
     */
    @Test
    public void deliveryTest() {
        // TODO: test delivery
    }

    /**
     * Test the property 'forceCollectComplianceInformation'
     */
    @Test
    public void forceCollectComplianceInformationTest() {
        // TODO: test forceCollectComplianceInformation
    }

    /**
     * Test the property 'additionalSteps'
     */
    @Test
    public void additionalStepsTest() {
        // TODO: test additionalSteps
    }

    /**
     * Test the property 'taxExempt'
     */
    @Test
    public void taxExemptTest() {
        // TODO: test taxExempt
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'idempotencyKey'
     */
    @Test
    public void idempotencyKeyTest() {
        // TODO: test idempotencyKey
    }

    /**
     * Test the property 'payoutFeeParty'
     */
    @Test
    public void payoutFeePartyTest() {
        // TODO: test payoutFeeParty
    }

}
