/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TransferbatchesCreateBatchRequestItemsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransferbatchesCreateBatchRequest
 */
public class TransferbatchesCreateBatchRequestTest {
    private final TransferbatchesCreateBatchRequest model = new TransferbatchesCreateBatchRequest();

    /**
     * Model tests for TransferbatchesCreateBatchRequest
     */
    @Test
    public void testTransferbatchesCreateBatchRequest() {
        // TODO: test TransferbatchesCreateBatchRequest
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'idempotencyKey'
     */
    @Test
    public void idempotencyKeyTest() {
        // TODO: test idempotencyKey
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
