/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UsersSubmitComplianceInfoRequestW8benAddress;
import com.konfigthis.client.model.UsersSubmitComplianceInfoRequestW8benSignature;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsersSubmitComplianceInfoRequestW8ben
 */
public class UsersSubmitComplianceInfoRequestW8benTest {
    private final UsersSubmitComplianceInfoRequestW8ben model = new UsersSubmitComplianceInfoRequestW8ben();

    /**
     * Model tests for UsersSubmitComplianceInfoRequestW8ben
     */
    @Test
    public void testUsersSubmitComplianceInfoRequestW8ben() {
        // TODO: test UsersSubmitComplianceInfoRequestW8ben
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'citizenshipCountry'
     */
    @Test
    public void citizenshipCountryTest() {
        // TODO: test citizenshipCountry
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'tin'
     */
    @Test
    public void tinTest() {
        // TODO: test tin
    }

    /**
     * Test the property 'foreignTaxId'
     */
    @Test
    public void foreignTaxIdTest() {
        // TODO: test foreignTaxId
    }

    /**
     * Test the property 'taxTreatyCountry'
     */
    @Test
    public void taxTreatyCountryTest() {
        // TODO: test taxTreatyCountry
    }

    /**
     * Test the property 'taxTreatyCitation'
     */
    @Test
    public void taxTreatyCitationTest() {
        // TODO: test taxTreatyCitation
    }

    /**
     * Test the property 'taxTreatyRate'
     */
    @Test
    public void taxTreatyRateTest() {
        // TODO: test taxTreatyRate
    }

    /**
     * Test the property 'taxTreatyIncomeType'
     */
    @Test
    public void taxTreatyIncomeTypeTest() {
        // TODO: test taxTreatyIncomeType
    }

    /**
     * Test the property 'taxTreatyExplanation'
     */
    @Test
    public void taxTreatyExplanationTest() {
        // TODO: test taxTreatyExplanation
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

}
