/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Wallet
 */
public class WalletTest {
    private final Wallet model = new Wallet();

    /**
     * Model tests for Wallet
     */
    @Test
    public void testWallet() {
        // TODO: test Wallet
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'withdrawableAmount'
     */
    @Test
    public void withdrawableAmountTest() {
        // TODO: test withdrawableAmount
    }

    /**
     * Test the property 'creditBalance'
     */
    @Test
    public void creditBalanceTest() {
        // TODO: test creditBalance
    }

}
