/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AppMetrics
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AppMetrics {
  public static final String SERIALIZED_NAME_WALLET_BALANCE = "wallet_balance";
  @SerializedName(SERIALIZED_NAME_WALLET_BALANCE)
  private BigDecimal walletBalance;

  public static final String SERIALIZED_NAME_MONEY_OUT = "money_out";
  @SerializedName(SERIALIZED_NAME_MONEY_OUT)
  private BigDecimal moneyOut;

  public static final String SERIALIZED_NAME_CONNECTED_USERS = "connected_users";
  @SerializedName(SERIALIZED_NAME_CONNECTED_USERS)
  private Integer connectedUsers;

  public AppMetrics() {
  }

  public AppMetrics walletBalance(BigDecimal walletBalance) {
    
    
    
    
    this.walletBalance = walletBalance;
    return this;
  }

   /**
   * Get walletBalance
   * @return walletBalance
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getWalletBalance() {
    return walletBalance;
  }


  public void setWalletBalance(BigDecimal walletBalance) {
    
    
    
    this.walletBalance = walletBalance;
  }


  public AppMetrics moneyOut(BigDecimal moneyOut) {
    
    
    
    
    this.moneyOut = moneyOut;
    return this;
  }

   /**
   * Get moneyOut
   * @return moneyOut
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getMoneyOut() {
    return moneyOut;
  }


  public void setMoneyOut(BigDecimal moneyOut) {
    
    
    
    this.moneyOut = moneyOut;
  }


  public AppMetrics connectedUsers(Integer connectedUsers) {
    
    
    
    
    this.connectedUsers = connectedUsers;
    return this;
  }

   /**
   * Get connectedUsers
   * @return connectedUsers
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getConnectedUsers() {
    return connectedUsers;
  }


  public void setConnectedUsers(Integer connectedUsers) {
    
    
    
    this.connectedUsers = connectedUsers;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AppMetrics instance itself
   */
  public AppMetrics putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppMetrics appMetrics = (AppMetrics) o;
    return Objects.equals(this.walletBalance, appMetrics.walletBalance) &&
        Objects.equals(this.moneyOut, appMetrics.moneyOut) &&
        Objects.equals(this.connectedUsers, appMetrics.connectedUsers)&&
        Objects.equals(this.additionalProperties, appMetrics.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletBalance, moneyOut, connectedUsers, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppMetrics {\n");
    sb.append("    walletBalance: ").append(toIndentedString(walletBalance)).append("\n");
    sb.append("    moneyOut: ").append(toIndentedString(moneyOut)).append("\n");
    sb.append("    connectedUsers: ").append(toIndentedString(connectedUsers)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("wallet_balance");
    openapiFields.add("money_out");
    openapiFields.add("connected_users");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("wallet_balance");
    openapiRequiredFields.add("money_out");
    openapiRequiredFields.add("connected_users");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AppMetrics
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AppMetrics.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AppMetrics is not found in the empty JSON string", AppMetrics.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AppMetrics.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("wallet_balance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `wallet_balance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wallet_balance").toString()));
      }
      if (!jsonObj.get("money_out").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `money_out` to be a primitive type in the JSON string but got `%s`", jsonObj.get("money_out").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AppMetrics.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AppMetrics' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AppMetrics> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AppMetrics.class));

       return (TypeAdapter<T>) new TypeAdapter<AppMetrics>() {
           @Override
           public void write(JsonWriter out, AppMetrics value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AppMetrics read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AppMetrics instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AppMetrics given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AppMetrics
  * @throws IOException if the JSON string is invalid with respect to AppMetrics
  */
  public static AppMetrics fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AppMetrics.class);
  }

 /**
  * Convert an instance of AppMetrics to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

