/*
 * dots api
 * Scalable and Flexible Payouts Infrastructure
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@dots.dev
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UsersSubmitComplianceInfoRequestW8ben;
import com.konfigthis.client.model.UsersSubmitComplianceInfoRequestW9;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UsersSubmitComplianceInfoRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UsersSubmitComplianceInfoRequest {
  public static final String SERIALIZED_NAME_W9 = "w9";
  @SerializedName(SERIALIZED_NAME_W9)
  private UsersSubmitComplianceInfoRequestW9 w9;

  public static final String SERIALIZED_NAME_W8BEN = "w8ben";
  @SerializedName(SERIALIZED_NAME_W8BEN)
  private UsersSubmitComplianceInfoRequestW8ben w8ben;

  public UsersSubmitComplianceInfoRequest() {
  }

  public UsersSubmitComplianceInfoRequest w9(UsersSubmitComplianceInfoRequestW9 w9) {
    
    
    
    
    this.w9 = w9;
    return this;
  }

   /**
   * Get w9
   * @return w9
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UsersSubmitComplianceInfoRequestW9 getW9() {
    return w9;
  }


  public void setW9(UsersSubmitComplianceInfoRequestW9 w9) {
    
    
    
    this.w9 = w9;
  }


  public UsersSubmitComplianceInfoRequest w8ben(UsersSubmitComplianceInfoRequestW8ben w8ben) {
    
    
    
    
    this.w8ben = w8ben;
    return this;
  }

   /**
   * Get w8ben
   * @return w8ben
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UsersSubmitComplianceInfoRequestW8ben getW8ben() {
    return w8ben;
  }


  public void setW8ben(UsersSubmitComplianceInfoRequestW8ben w8ben) {
    
    
    
    this.w8ben = w8ben;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UsersSubmitComplianceInfoRequest instance itself
   */
  public UsersSubmitComplianceInfoRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersSubmitComplianceInfoRequest usersSubmitComplianceInfoRequest = (UsersSubmitComplianceInfoRequest) o;
    return Objects.equals(this.w9, usersSubmitComplianceInfoRequest.w9) &&
        Objects.equals(this.w8ben, usersSubmitComplianceInfoRequest.w8ben)&&
        Objects.equals(this.additionalProperties, usersSubmitComplianceInfoRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(w9, w8ben, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersSubmitComplianceInfoRequest {\n");
    sb.append("    w9: ").append(toIndentedString(w9)).append("\n");
    sb.append("    w8ben: ").append(toIndentedString(w8ben)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("w9");
    openapiFields.add("w8ben");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UsersSubmitComplianceInfoRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UsersSubmitComplianceInfoRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UsersSubmitComplianceInfoRequest is not found in the empty JSON string", UsersSubmitComplianceInfoRequest.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `w9`
      if (jsonObj.get("w9") != null && !jsonObj.get("w9").isJsonNull()) {
        UsersSubmitComplianceInfoRequestW9.validateJsonObject(jsonObj.getAsJsonObject("w9"));
      }
      // validate the optional field `w8ben`
      if (jsonObj.get("w8ben") != null && !jsonObj.get("w8ben").isJsonNull()) {
        UsersSubmitComplianceInfoRequestW8ben.validateJsonObject(jsonObj.getAsJsonObject("w8ben"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsersSubmitComplianceInfoRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsersSubmitComplianceInfoRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsersSubmitComplianceInfoRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsersSubmitComplianceInfoRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UsersSubmitComplianceInfoRequest>() {
           @Override
           public void write(JsonWriter out, UsersSubmitComplianceInfoRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UsersSubmitComplianceInfoRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UsersSubmitComplianceInfoRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UsersSubmitComplianceInfoRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UsersSubmitComplianceInfoRequest
  * @throws IOException if the JSON string is invalid with respect to UsersSubmitComplianceInfoRequest
  */
  public static UsersSubmitComplianceInfoRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsersSubmitComplianceInfoRequest.class);
  }

 /**
  * Convert an instance of UsersSubmitComplianceInfoRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

